name: havatar
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  # PyTorch and related libraries for deep learning and 3D processing
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pytorch3d

  # Core libraries for scientific computing and image processing
  - numpy
  - opencv
  - scikit-image
  - scipy

  # Utilities
  - pyyaml
  - tqdm
  - einops

  # For ONNX model support (used in data preprocessing)
  - onnxruntime

  # For visualization
  - matplotlib

  # For compiling custom C++/CUDA extensions
  - setuptools

  # Libraries to be installed with pip
  - pip:
    - lpips
    - mediapipe
    - geffnet